#basics of R with L10 reg 1 dataset


file=read.csv(file.choose(),header = TRUE)
head(file)
tail(file)
head(file,7)
tail(file,7)
nrow(file)
ncol(file)
colnames(file)
summary(file)
mean(file$Price)
max(file$LivingArea)
min(file$LotSize)
unique(file$Fireplace)
table(file$Fireplace)
table(file$Bedrooms)
unique(file$Bedrooms)
tapply(file$Price,file$Bedrooms,mean)
apply(file,2,sum)
apply(file,2,mean)
apply(file,2,max)
max(file$Price)
max(file$Bathrooms)
table(file$Bathrooms)
max(file$Age)
cor(file)
cor.test(file$Price,file$LivingArea)
